name: Convert and Push Adoc

on:
  workflow_dispatch:

jobs:
  convert_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Use v2 version for private repositories
        with:
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.SOURCE_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Convert and Push Test Plan Adoc
        run: |
          wget https://raw.githubusercontent.com/CHIP-Specifications/chip-test-plans/main/html/allclusters.html
          pandoc -f html -t adoc allclusters.html -o Docs/Test_Plan_Adoc/allclusters.adoc
          git add Docs/Test_Plan_Adoc/allclusters.adoc
          git commit -m "Added allclusters.adoc"
          git push

          wget https://raw.githubusercontent.com/CHIP-Specifications/chip-test-plans/main/html/index.html
          pandoc -f html -t adoc index.html -o Docs/Test_Plan_Adoc/index.adoc
          git add Docs/Test_Plan_Adoc/index.adoc
          git commit -m "Added index.adoc"
          git push

      - name: Convert and Push SPEC Adoc
        run: |
          wget https://raw.githubusercontent.com/CHIP-Specifications/connectedhomeip-spec/main/html/appclusters.html
          pandoc -f html -t adoc appclusters.html -o Docs/SPEC_Adoc/appclusters.adoc
          git add Docs/SPEC_Adoc/appclusters.adoc
          git commit -m "Added appclusters.adoc"
          git push

          wget https://raw.githubusercontent.com/CHIP-Specifications/connectedhomeip-spec/main/html/index.html
          pandoc -f html -t adoc index.html -o Docs/SPEC_Adoc/index.adoc
          git add Docs/SPEC_Adoc/index.adoc
          git commit -m "Added index.adoc"
          git push
